[package]
name = "datetag"
version = "0.1.0"
authors = ["Daniele Olmisani <mad4j@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
structopt = "0.3"
colored = "2.0"
anyhow = "1.0"
