[package]
name = "datetag"
version = "0.1.3"
authors = ["Daniele Olmisani <daniele.olmisani@gmail.com>"]
license = "GPL-3.0"
edition = "2021"
description = "datetag is a simple application to generatate e manage date tags"
readme = "README.md"
homepage = "https://mad4j.github.io/rusted-datetag/"
repository = "https://github.com/mad4j/rusted-datetag"
keywords = ["cli", "date", "tag"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
structopt = "0.3"
anyhow = "1.0"
